version: "3.8"

services:
  nginx:
    image: nginx:1.14.2
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf.template
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      SERVICE_NAME: "target-service"
      AUTH_TYPE: "jwt"
      TARGET_SERVICE_HOST: target-service
      TARGET_SERVICE_PORT: 8080
      MIRROR_SERVICE_HOST: monitoring-producer
      MIRROR_SERVICE_PORT: 8081
    entrypoint: /docker-entrypoint.sh
    command: [ "nginx-debug", "-g", "daemon off;" ]
  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  target-service:
    image: target-service:0.0.1-SNAPSHOT
  monitoring-producer:
    image: monitoring-producer:0.0.1-SNAPSHOT
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin