version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf.template
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      SERVICE_NAME: "target-service"
      AUTH_TYPE: "synapse"
      TARGET_SERVICE_HOST: target-service
      TARGET_SERVICE_PORT: 8080
      MIRROR_SERVICE_HOST: host.docker.internal
      MIRROR_SERVICE_PORT: 8081
    entrypoint: /docker-entrypoint.sh
    command: [ "nginx-debug", "-g", "daemon off;" ]
  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  target-service:
    image: target-service:0.0.1-SNAPSHOT
  elastic: #TODO: configure elastic security
    image: elasticsearch:7.17.1
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: elastic
      LICENSE: basic
    ports:
      - "9200:9200"
  grafana: #TODO: add template variables to dashboard
    image: grafana/grafana
    ports:
      - "3000:3000"