version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf.template
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      SERVICE_NAME: "target-service"
      AUTH_TYPE: "/synapse"
      TARGET_SERVICE_HOST: target-service
      TARGET_SERVICE_PORT: 8080
      MIRROR_SERVICE_HOST: host.docker.internal
      MIRROR_SERVICE_PORT: 8081
    entrypoint: /docker-entrypoint.sh
    command: [ "nginx-debug", "-g", "daemon off;" ]
  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  target-service:
    image: target-service:0.0.1-SNAPSHOT
  elastic:
    image: arm64v8/elasticsearch:7.8.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: elastic
      LICENSE: basic
    ports:
      - "9200:9200"
  grafana:
    image: grafana/grafana:8.2.7
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      ELASTIC_INDEX: requests
      ELASTIC_HOST: elastic
      ELASTIC_PORT: 9200
      ELASTIC_USER: elastic
      ELASTIC_PASSWORD: elastic
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: monitoring
    ports:
      - "5432:5432"

