apiVersion: v1
kind: Service
metadata:
  name: monitoring-producer-service
  labels:
    app: monitoring-producer-service
spec:
  ports:
    - port: 8080
  selector:
    app: monitoring-producer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-producer
  labels:
    app: monitoring-producer
spec:
  selector:
    matchLabels:
      app: monitoring-producer
  template:
    metadata:
      labels:
        app: monitoring-producer
    spec:
      containers:
        - name: monitoring-producer
          image: monitoring-producer:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              value: rabbit-service
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: admin
            - name: RABBITMQ_PASSWORD
              value: admin
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
