apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-consumer
  labels:
    app: monitoring-consumer
spec:
  selector:
    matchLabels:
      app: monitoring-consumer
  template:
    metadata:
      labels:
        app: monitoring-consumer
    spec:
      containers:
        - name: monitoring-consumer
          image: monitoring-consumer:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq-service.default.svc.cluster.local
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: admin
            - name: RABBITMQ_PASSWORD
              value: admin