apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-service
  labels:
    app: rabbitmq-service
spec:
  type: NodePort
  ports:
    - port: 15672
  selector:
    app: rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
spec:
  ports:
    - port: 5672
  selector:
    app: rabbitmq

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.2-management
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: admin
          ports:
            - containerPort: 5672
            - containerPort: 15672
