apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: $ELASTIC_INDEX
    url: http://$ELASTIC_HOST:$ELASTIC_PORT
    uid: gdev-elasticsearch # do not change this. If you do you'll have to change all the datasource uids in dashboard template
    basicAuth: true
    basicAuthUser: $ELASTIC_USER
    basicAuthPassword: $ELASTIC_PASSWORD
    jsonData:
      timeField: "@timestamp"
      esVersion: 70
      timeInterval: "1s"