apiVersion: v1
kind: Service
metadata:
  name: monitoring-producer-service
  labels:
    app: monitoring-producer-service
spec:
  ports:
    - port: 8080
      targetPort: producer-port
  selector:
    app: monitoring-producer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-producer
  labels:
    app: monitoring-producer
spec:
  selector:
    matchLabels:
      app: monitoring-producer
  template:
    metadata:
      labels:
        app: monitoring-producer
    spec:
      containers:
        - name: monitoring-producer
          image: monitoring-producer:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: rabbitmq-host
                  name: rabbitmq-connectivity
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: rabbitmq-port
                  name: rabbitmq-connectivity
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-username
                  name: rabbitmq-secrets
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-password
                  name: rabbitmq-secrets
            - name: SERVER_PORT
              value: "8080"
          ports:
            - name: producer-port
              containerPort: 8080
